apiVersion: v1
kind: Service
metadata:
  name: {{ include "patentsearchgraphfullname" . }}
  labels:
    {{- include "patentsearchgraphlabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "patentsearchgraphselectorLabels" . | nindent 4 }}
